name: Lint & Test

on:
  push:
    branches-ignore:
      - main
      - release
  pull_request:
    branches:
      - release

env:
  NODE_VERSION: ${{ 18 }}

jobs:
  setup:
    uses: kevink01/kevin-utils-old2/.github/workflows/setup.yml@main
    with:
      NODE_VERSION: ${{ env.NODE_VERSION }}
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Lint codebase
        run: pnpm lint

      - name: Test functions
        run: pnpm test

      - name: Build application
        run: pnpm build