name: Lint & Test

on:
  push:
    branch:
      - main
    branches-ignore:
      - release
  pull_request:
    branches:
      - release

env:
  NODE_VERSION: ${{ 18 }}

jobs:
  setup:
    uses: kevink01/kevin-utils-old2/.github/workflows/setup.yml@main
  dev:
    needs: 'setup'
    runs-on: ubuntu-latest
    steps:
      - name: Lint codebase
        run: pnpm lint

      - name: Test functions
        run: pnpm test

      - name: Build application
        run: pnpm build